type Property = {
  id: number;
  name: string;
  bedrooms: number;
  bathrooms: number;
  area: number;
  description: string;
  location: string;
  price: number;
  image: string;
};

export let properties: Property[] = [
  {
    id: 1,
    name: "Evergreen Retreat",
    bedrooms: 3,
    bathrooms: 2,
    area: 2200,
    description: "Cozy cabin nestled in the lush forests of Olympic National Park.",
    location: "Port Angeles, Washington",
    price: 450000,
    image: "https://themes.muffingroup.com/be/estate3/wp-content/uploads/2020/05/estate3-desc-pic1.jpg",
  },
  {
    id: 2,
    name: "Coastal Haven",
    bedrooms: 4,
    bathrooms: 3.5,
    area: 3100,
    description: "Stunning beachfront property with panoramic views of the Pacific Ocean.",
    location: "Cannon Beach, Oregon",
    price: 1200000,
    image: "https://themes.muffingroup.com/be/estate3/wp-content/uploads/2020/05/estate3-gallery-pic3.jpg",
  },
  {
    id: 3,
    name: "Urban Loft",
    bedrooms: 2,
    bathrooms: 2,
    area: 1500,
    description: "Modern loft in the heart of downtown Portland with skyline views.",
    location: "Portland, Oregon",
    price: 650000,
    image: "https://themes.muffingroup.com/be/estate3/wp-content/uploads/2020/05/estate3-gallery-pic4.jpg",
  },
  {
    id: 4,
    name: "Mountain Vista",
    bedrooms: 5,
    bathrooms: 4,
    area: 4000,
    description: "Luxurious mountain home with spectacular views of Mount Rainier.",
    location: "Issaquah, Washington",
    price: 1800000,
    image: "https://themes.muffingroup.com/be/estate3/wp-content/uploads/2020/05/estate3-slider-pic2.jpg",
  },
  {
    id: 5,
    name: "Riverside Cottage",
    bedrooms: 2,
    bathrooms: 1.5,
    area: 1200,
    description: "Charming cottage on the banks of the Willamette River.",
    location: "Eugene, Oregon",
    price: 375000,
    image: "https://themes.muffingroup.com/be/estate3/wp-content/uploads/2020/05/estate3-gallery-pic8.jpg",
  },
  {
    id: 6,
    name: "Seattle Skyline Penthouse",
    bedrooms: 3,
    bathrooms: 3,
    area: 2800,
    description: "Luxurious penthouse apartment with breathtaking views of the Space Needle.",
    location: "Seattle, Washington",
    price: 2200000,
    image: "https://themes.muffingroup.com/be/estate3/wp-content/uploads/2020/05/estate3-gallery-pic2.jpg",
  },
  {
    id: 7,
    name: "Vineyard Estate",
    bedrooms: 4,
    bathrooms: 3.5,
    area: 3500,
    description: "Elegant estate surrounded by rolling hills and private vineyards.",
    location: "Willamette Valley, Oregon",
    price: 1500000,
    image: "https://themes.muffingroup.com/be/estate2/wp-content/uploads/2018/07/home_estate2_pic3.jpg",
  },
  {
    id: 8,
    name: "Lakeside Retreat",
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    description: "Serene property on the shores of Lake Chelan with private dock.",
    location: "Chelan, Washington",
    price: 780000,
    image: "https://themes.muffingroup.com/be/estate3/wp-content/uploads/2020/05/estate3-slider-pic3.jpg",
  },
  {
    id: 9,
    name: "Historic Victorian",
    bedrooms: 5,
    bathrooms: 3.5,
    area: 3200,
    description: "Beautifully restored Victorian home in the heart of Astoria.",
    location: "Astoria, Oregon",
    price: 950000,
    image: "https://themes.muffingroup.com/be/estate3/wp-content/uploads/2020/05/estate3-gallery-pic4.jpg",
  },
  {
    id: 10,
    name: "Eco-Friendly Treehouse",
    bedrooms: 1,
    bathrooms: 1,
    area: 800,
    description: "Unique, sustainable treehouse retreat in the Cascade Mountains.",
    location: "Leavenworth, Washington",
    price: 325000,
    image: "https://themes.muffingroup.com/be/estate3/wp-content/uploads/2020/05/estate3-gallery-pic5.jpg",
  },
  {
    id: 11,
    name: "Columbia River Gorge Villa",
    bedrooms: 4,
    bathrooms: 3,
    area: 3000,
    description: "Stunning villa overlooking the Columbia River Gorge National Scenic Area.",
    location: "Hood River, Oregon",
    price: 1350000,
    image: "https://themes.muffingroup.com/be/estate3/wp-content/uploads/2020/05/estate3-gallery-pic6.jpg",
  },
  {
    id: 12,
    name: "San Juan Island Getaway",
    bedrooms: 3,
    bathrooms: 2.5,
    area: 2400,
    description: "Picturesque island home with whale watching opportunities from the deck.",
    location: "Friday Harbor, Washington",
    price: 890000,
    image: "https://themes.muffingroup.com/be/estate2/wp-content/uploads/2018/07/home_estate2_pic1.jpg",
  },
  {
    id: 13,
    name: "Pacific Coastal",
    bedrooms: 3,
    bathrooms: 2,
    area: 2200,
    description: "Elegant property with ocean views and private beach.",
    location: "Portland, Oregon",
    price: 1200000,
    image: "https://themes.muffingroup.com/be/estate3/wp-content/uploads/2020/05/estate3-gallery-pic1.jpg",
  },
  {
    id: 14,
    name: "Coastal Haven",
    bedrooms: 4,
    bathrooms: 3.5,
    area: 3100,
    description: "Stunning beachfront property with panoramic views of the Pacific Ocean.",
    location: "Cannon Beach, Oregon",
    price: 1200000,
    image: "https://themes.muffingroup.com/be/estate3/wp-content/uploads/2020/05/estate3-gallery-pic3.jpg",
  },
  {
    id: 15,
    name: "Urban Loft",
    bedrooms: 2,
    bathrooms: 2,
    area: 1500,
    description: "Modern loft in the heart of downtown Portland with skyline views.",
    location: "Portland, Oregon",
    price: 650000,
    image: "https://themes.muffingroup.com/be/estate3/wp-content/uploads/2020/05/estate3-gallery-pic4.jpg",
  },
];
