<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 static/devices.glb --transform --types -s --resolution 2048 --suspense
-->

<script lang="ts">
  import type * as THREE from "three";
  import { Group } from "three";
  import type { Snippet } from "svelte";
  import { T, type Props } from "@threlte/core";
  import { useGltf, useDraco, useGltfAnimations, useSuspense } from "@threlte/extras";

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    macbookRotation = [0, 0, 0],
    iPhonePosition = [0, 0, 0],
    iPhoneRotation = [0, 0, 0],
    actions = $bindable(),
    mixer = $bindable(),
    settings,
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group;
    children?: Snippet<[{ ref: THREE.Group }]>;
    fallback?: Snippet;
    error?: Snippet<[{ error: Error }]>;
    macbookRotation?: [number, number, number];
    iPhonePosition?: [number, number, number];
    iPhoneRotation?: [number, number, number];
    actions?: any;
    mixer?: any;
    settings?: any;
  } = $props();

  const suspend = useSuspense();

  ref = new Group();

  type ActionName = "Animation";
  type GLTFResult = {
    nodes: {
      QvGDcbDApaGssma: THREE.Mesh;
      MGPAkjCLsByKXcN: THREE.Mesh;
      vFwJFNASGvEHWhs: THREE.Mesh;
      fjHkOQLEMoyeYKr: THREE.Mesh;
      RvfXLdAOBoQdZkP: THREE.Mesh;
      VTXyqxbrBeQSTEt: THREE.Mesh;
      evAxFwhaQUwXuua: THREE.Mesh;
      USxQiqZgxHbRvqB: THREE.Mesh;
      TvgBVmqNmSrFVfW: THREE.Mesh;
      HKHhmqmAZAOaaKY: THREE.Mesh;
      IZQgEjTfhbNtjHR: THREE.Mesh;
      xJhdvBbfHMKCBPl: THREE.Mesh;
      eYSJBzbqIfsHPsw: THREE.Mesh;
      KbMHiTYyrBmkZwz: THREE.Mesh;
      sVqcZvpZKhwSmoN: THREE.Mesh;
      GuYJryuYunhpphO: THREE.Mesh;
      DOjZomXdJsbbvcr: THREE.Mesh;
      cnreaSmJRdAuFia: THREE.Mesh;
      pvdHknDTGDzVpwc: THREE.Mesh;
      CfghdUoyzvwzIum: THREE.Mesh;
      MHfUXxLdYldKhVJ_0: THREE.Mesh;
      TxLQyfBdakwBPHu_0: THREE.Mesh;
      DjsDkGiopeiEJZK: THREE.Mesh;
      zraMDXCGczVnffU: THREE.Mesh;
      buRWvyqhBBgcJFo: THREE.Mesh;
      MrMmlCAsAxJpYqQ_0: THREE.Mesh;
      KVYuugCtKRpLNRG_0: THREE.Mesh;
      wqbHSzWaUxBCwxY_0: THREE.Mesh;
      xXDHkMplTIDAXLN: THREE.Mesh;
      IZbjANwSMLfgcvD: THREE.Mesh;
      SysBlPspVQNIcce: THREE.Mesh;
      vELORlCJixqPHsZ: THREE.Mesh;
      IMPDFDiRXhPIUMV: THREE.Mesh;
      EbQGKrWAqhBHiMv: THREE.Mesh;
      EddVrWkqZTlvmci: THREE.Mesh;
      aGrbyjnzqoVJenz: THREE.Mesh;
      KSWlaxBcnPDpFCs: THREE.Mesh;
      AQkWXGdRSkSZMav: THREE.Mesh;
      DjdhycfQYjKMDyn: THREE.Mesh;
      usFLmqcyrnltBUr: THREE.Mesh;
      TakBsdEjEytCAMK: THREE.Mesh;
      IykfmVvLplTsTEW: THREE.Mesh;
      wLfSXtbwRlBrwof: THREE.Mesh;
      WJwwVjsahIXbJpU: THREE.Mesh;
      cibcwsZWGgGfpme: THREE.Mesh;
      YfrJNXgMvGOAfzz: THREE.Mesh;
      DCLCbjzqejuvsqH: THREE.Mesh;
      dkQXkqysxzfHFiP: THREE.Mesh;
      FscwyiLIVNWUuKe: THREE.Mesh;
      CdalkzDVnwgdEhS: THREE.Mesh;
      NtjcIgolNGgYlCg: THREE.Mesh;
      zOPceDOPdLNSscX: THREE.Mesh;
      bxjlJpbNESedyat: THREE.Mesh;
      ehFpgEdYijLjwka: THREE.Mesh;
      IXWuqsIeTqBFLIy: THREE.Mesh;
      qlwPlhojsxIgqwa: THREE.Mesh;
      bpqFtgUKAOOPYpk: THREE.Mesh;
      dxVZiHfQBLkPYHO: THREE.Mesh;
      guvLdFXlBjMoNra: THREE.Mesh;
      PRPzbUhYhabBDYt: THREE.Mesh;
      oOTDgAlTGbFYzBo: THREE.Mesh;
      hGKQDeRmDnGNdjb: THREE.Mesh;
      XRoKUoMkItkzNYL: THREE.Mesh;
      FjtgRCsnzEoHpCy: THREE.Mesh;
      gJeeYWdxrKsnsVD: THREE.Mesh;
      KOgQmlOdVEyKocf: THREE.Mesh;
      gTmqYtKthFeRVJL: THREE.Mesh;
      obVkazjvaXyXFtA: THREE.Mesh;
      zFlMfSCaOdRDBFx: THREE.Mesh;
      ooeiSEXgcJckXsp: THREE.Mesh;
      lfXEACUihtLFGfq: THREE.Mesh;
      eWbcqPskBBXuZDe: THREE.Mesh;
      AdjkxvMXIDEHBMM: THREE.Mesh;
      drpRvcOgsocXGbn: THREE.Mesh;
      KXVnYLSfTdVnSOf: THREE.Mesh;
      FFAjDZTPwYrUKAV: THREE.Mesh;
      AwsQCWysocWlYzN: THREE.Mesh;
      wJqHahKxdxecSAC: THREE.Mesh;
      SRYqzKwamLGuEGm: THREE.Mesh;
      yxqQUnbopbiRvZr: THREE.Mesh;
      xtMgDHhPqFLAHyB: THREE.Mesh;
      nnqwwoLVdMJlHIF: THREE.Mesh;
      pXBNoLiaMwsDHRF: THREE.Mesh;
      SCoTCDlNLPQMMyt: THREE.Mesh;
      fdZyCEcqJDKBWVW: THREE.Mesh;
      IkoiNqATMVoZFKD: THREE.Mesh;
      rqgRAGHOwnuBypi: THREE.Mesh;
      npMJxzurVJQlumk: THREE.Mesh;
      ttmRoLdJipiIOmf: THREE.Mesh;
      Object_12: THREE.Mesh;
      Object_4: THREE.Mesh;
      Object_5: THREE.Mesh;
      Object_6: THREE.Mesh;
      Object_7: THREE.Mesh;
      Object_8: THREE.Mesh;
      Object_9: THREE.Mesh;
      Object_14: THREE.Mesh;
      Object_16: THREE.Mesh;
      Object_18: THREE.Mesh;
      Object_19: THREE.Mesh;
      Object_20: THREE.Mesh;
      Object_21: THREE.Mesh;
      Object_23: THREE.Mesh;
      Object_24: THREE.Mesh;
      Object_25: THREE.Mesh;
      Object_27: THREE.Mesh;
      Object_29: THREE.Mesh;
      Object_30: THREE.Mesh;
      Object_32: THREE.Mesh;
    };
    materials: {
      kUhjpatHUvkBwfM: THREE.MeshStandardMaterial;
      RJoymvEsaIItifI_0_1: THREE.MeshStandardMaterial;
      AhrzSsKcKjghXhP_0_1: THREE.MeshStandardMaterial;
      hUlRcbieVuIiOXG_0_1: THREE.MeshStandardMaterial;
      eHgELfGhsUorIYR_0_1: THREE.MeshStandardMaterial;
      KSIxMqttXxxmOYl_0_1: THREE.MeshStandardMaterial;
      mcPrzcBUcdqUybC_0_1: THREE.MeshStandardMaterial;
      pIhYLPqiSQOZTjn: THREE.MeshStandardMaterial;
      dxCVrUCvYhjVxqy: THREE.MeshStandardMaterial;
      eShKpuMNVJTRrgg: THREE.MeshStandardMaterial;
      xdyiJLYTYRfJffH: THREE.MeshStandardMaterial;
      jpGaQNgTtEGkTfo: THREE.MeshStandardMaterial;
      iCxrnlRvbVOguYp_0_1: THREE.MeshStandardMaterial;
      mvjnAONQuIshyfX: THREE.MeshStandardMaterial;
      MHFGNLrDQbTNima: THREE.MeshStandardMaterial;
      pIJKfZsazmcpEiU_0_1: THREE.MeshStandardMaterial;
      ujsvqBWRMnqdwPx_0_1: THREE.MeshStandardMaterial;
      zFdeDaGNRwzccye_0_1: THREE.MeshStandardMaterial;
      TBLSREBUyLMVtJa_0_1: THREE.MeshStandardMaterial;
      xNrofRCqOXXHVZt_0_1: THREE.MeshStandardMaterial;
      yQQySPTfbEJufve_0_1: THREE.MeshStandardMaterial;
      sxNzrmuTqVeaXdg_0_1: THREE.MeshStandardMaterial;
      ZQfGMLaFcpPaLMU_0_1: THREE.MeshStandardMaterial;
      dwrMminMXjXXeek_0_1: THREE.MeshStandardMaterial;
      oZRkkORNzkufnGD: THREE.MeshStandardMaterial;
      yhcAXNGcJWCqtIS: THREE.MeshStandardMaterial;
      bCgzXjHOanGdTFV_0_1: THREE.MeshStandardMaterial;
      vhaEJjZoqGtyLdo_0_1: THREE.MeshStandardMaterial;
      fkUApOHLQsMUdfd_0_1: THREE.MeshStandardMaterial;
      jlzuBkUzuJqgiAK_0_1: THREE.MeshStandardMaterial;
      PpwUTnTFZJXxCoE: THREE.MeshStandardMaterial;
      EuTsEfyoAnyJIih_0_1: THREE.MeshStandardMaterial;
      EszxgwYUTxbhBrC_0_1: THREE.MeshStandardMaterial;
      yiDkEwDSyEhavuP: THREE.MeshStandardMaterial;
      hiVunnLeAHkwGEo: THREE.MeshStandardMaterial;
      HGhEhpqSBZRnjHC: THREE.MeshStandardMaterial;
      JJvGZqtXqnnFakR_0_1: THREE.MeshStandardMaterial;
      Camera_Light_0_1: THREE.MeshStandardMaterial;
      Black_Glass_0_1: THREE.MeshStandardMaterial;
      Black_Plastic_0_1: THREE.MeshStandardMaterial;
      Glass_0_1: THREE.MeshStandardMaterial;
      ["Material.002_0_1"]: THREE.MeshStandardMaterial;
      Space_Grey_0_1: THREE.MeshStandardMaterial;
      ["Space_Grey.001_0_1"]: THREE.MeshStandardMaterial;
      Caps_Lock_Light_0_1: THREE.MeshStandardMaterial;
      ["Material.001_0_1"]: THREE.MeshStandardMaterial;
      ["Keys.001_0_1"]: THREE.MeshStandardMaterial;
      Keys_0_1: THREE.MeshStandardMaterial;
      ["Touch_Bar_Shot_2021-04-02_at_18.13.28_0_1"]: THREE.MeshStandardMaterial;
    };
  };

  const dracoLoader = useDraco();
  const gltf = suspend(useGltf<GLTFResult>("src/routes/(examples)/phone/devices-transformed.glb", { dracoLoader }));

  export const { actions: gltfActions, mixer: gltfMixer } = useGltfAnimations<ActionName>(gltf, ref);

  // Bind animations to props
  $effect(() => {
    actions = gltfActions;
    mixer = gltfMixer;
  });
</script>

<T is={ref} dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Scene">
      {#if settings?.devices?.iPhoneEnabled !== false}
        <T.Group name="iphone" position={[-3 + iPhonePosition[0], iPhonePosition[1], iPhonePosition[2]]} rotation={[-1.57 + iPhoneRotation[0], iPhoneRotation[1], Math.PI + iPhoneRotation[2]]} scale={22.49}>
          <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
            <T.Group name="USDRoot" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
              <T.Group name="tracking_node_placeholder">
                <T.Group name="MBJPHxJFDgaTDhF">
                  <T.Group name="rVbvQyXCLAfnDro">
                    <T.Group name="rdkdGpTstFFbsnN">
                      <T.Group name="bMosPntExNwiJNs">
                        <T.Group name="HcyBnTbtxefaLfx">
                          <T.Group name="yOlFnklNiZttLOW">
                            <T.Mesh name="QvGDcbDApaGssma" geometry={gltf.nodes.QvGDcbDApaGssma.geometry} material={gltf.materials.kUhjpatHUvkBwfM} />
                            <T.Mesh name="MGPAkjCLsByKXcN" geometry={gltf.nodes.MGPAkjCLsByKXcN.geometry} material={gltf.materials.kUhjpatHUvkBwfM} />
                            <T.Mesh name="vFwJFNASGvEHWhs" geometry={gltf.nodes.vFwJFNASGvEHWhs.geometry} material={gltf.materials.RJoymvEsaIItifI_0_1} />
                            <T.Mesh name="fjHkOQLEMoyeYKr" geometry={gltf.nodes.fjHkOQLEMoyeYKr.geometry} material={gltf.materials.AhrzSsKcKjghXhP_0_1} />
                            <T.Mesh name="RvfXLdAOBoQdZkP" geometry={gltf.nodes.RvfXLdAOBoQdZkP.geometry} material={gltf.materials.hUlRcbieVuIiOXG_0_1} />
                            <T.Mesh name="VTXyqxbrBeQSTEt" geometry={gltf.nodes.VTXyqxbrBeQSTEt.geometry} material={gltf.materials.eHgELfGhsUorIYR_0_1} />
                            <T.Mesh name="evAxFwhaQUwXuua" geometry={gltf.nodes.evAxFwhaQUwXuua.geometry} material={gltf.materials.KSIxMqttXxxmOYl_0_1} />
                            <T.Mesh name="USxQiqZgxHbRvqB" geometry={gltf.nodes.USxQiqZgxHbRvqB.geometry} material={gltf.materials.mcPrzcBUcdqUybC_0_1} />
                          </T.Group>
                          <T.Group name="UoRZOKZDdwJJsVl">
                            <T.Mesh name="TvgBVmqNmSrFVfW" geometry={gltf.nodes.TvgBVmqNmSrFVfW.geometry} material={gltf.materials.pIhYLPqiSQOZTjn} />
                          </T.Group>
                          <T.Group name="ZoJjqNAakQjcNhW">
                            <T.Group name="ZUpoBLZWQSTiNbu">
                              <T.Mesh name="HKHhmqmAZAOaaKY" geometry={gltf.nodes.HKHhmqmAZAOaaKY.geometry} material={gltf.materials.dxCVrUCvYhjVxqy} />
                              <T.Mesh name="IZQgEjTfhbNtjHR" geometry={gltf.nodes.IZQgEjTfhbNtjHR.geometry} material={gltf.materials.eShKpuMNVJTRrgg} />
                            </T.Group>
                            <T.Mesh name="xJhdvBbfHMKCBPl" geometry={gltf.nodes.xJhdvBbfHMKCBPl.geometry} material={gltf.materials.dxCVrUCvYhjVxqy} />
                            <T.Mesh name="eYSJBzbqIfsHPsw" geometry={gltf.nodes.eYSJBzbqIfsHPsw.geometry} material={gltf.materials.hUlRcbieVuIiOXG_0_1} />
                            <T.Mesh name="KbMHiTYyrBmkZwz" geometry={gltf.nodes.KbMHiTYyrBmkZwz.geometry} material={gltf.materials.dxCVrUCvYhjVxqy} />
                            <T.Mesh name="sVqcZvpZKhwSmoN" geometry={gltf.nodes.sVqcZvpZKhwSmoN.geometry} material={gltf.materials.dxCVrUCvYhjVxqy} />
                            <T.Mesh name="GuYJryuYunhpphO" geometry={gltf.nodes.GuYJryuYunhpphO.geometry} material={gltf.materials.eShKpuMNVJTRrgg} />
                            <T.Mesh name="DOjZomXdJsbbvcr" geometry={gltf.nodes.DOjZomXdJsbbvcr.geometry} material={gltf.materials.eShKpuMNVJTRrgg} />
                            <T.Mesh name="cnreaSmJRdAuFia" geometry={gltf.nodes.cnreaSmJRdAuFia.geometry} material={gltf.materials.eShKpuMNVJTRrgg} />
                          </T.Group>
                          <T.Group name="gxFsxFJsSGiHLmU">
                            <T.Mesh name="pvdHknDTGDzVpwc" geometry={gltf.nodes.pvdHknDTGDzVpwc.geometry} material={gltf.materials.xdyiJLYTYRfJffH} />
                            <T.Mesh name="CfghdUoyzvwzIum" geometry={gltf.nodes.CfghdUoyzvwzIum.geometry} material={gltf.materials.jpGaQNgTtEGkTfo} />
                            <T.Mesh name="MHfUXxLdYldKhVJ_0" geometry={gltf.nodes.MHfUXxLdYldKhVJ_0.geometry} material={gltf.materials.dxCVrUCvYhjVxqy} />
                            <T.Mesh name="TxLQyfBdakwBPHu_0" geometry={gltf.nodes.TxLQyfBdakwBPHu_0.geometry} material={gltf.materials.eShKpuMNVJTRrgg} />
                          </T.Group>
                          <T.Mesh name="DjsDkGiopeiEJZK" geometry={gltf.nodes.DjsDkGiopeiEJZK.geometry} material={gltf.materials.iCxrnlRvbVOguYp_0_1} />
                          <T.Mesh name="zraMDXCGczVnffU" geometry={gltf.nodes.zraMDXCGczVnffU.geometry} material={gltf.materials.hUlRcbieVuIiOXG_0_1} />
                          <T.Mesh name="buRWvyqhBBgcJFo" geometry={gltf.nodes.buRWvyqhBBgcJFo.geometry} material={gltf.materials.eHgELfGhsUorIYR_0_1} />
                          <T.Mesh name="MrMmlCAsAxJpYqQ_0" geometry={gltf.nodes.MrMmlCAsAxJpYqQ_0.geometry} material={gltf.materials.dxCVrUCvYhjVxqy} />
                          <T.Mesh name="KVYuugCtKRpLNRG_0" geometry={gltf.nodes.KVYuugCtKRpLNRG_0.geometry} material={gltf.materials.mvjnAONQuIshyfX} />
                          <T.Mesh name="wqbHSzWaUxBCwxY_0" geometry={gltf.nodes.wqbHSzWaUxBCwxY_0.geometry} material={gltf.materials.MHFGNLrDQbTNima} />
                        </T.Group>
                        <T.Group name="mfFUMfbDmZhhOWo">
                          <T.Group name="HzsqHeSJsfveFUX">
                            <T.Mesh name="xXDHkMplTIDAXLN" geometry={gltf.nodes.xXDHkMplTIDAXLN.geometry} material={gltf.materials.pIJKfZsazmcpEiU_0_1} />
                            <T.Mesh name="IZbjANwSMLfgcvD" geometry={gltf.nodes.IZbjANwSMLfgcvD.geometry} material={gltf.materials.hUlRcbieVuIiOXG_0_1} />
                            <T.Mesh name="SysBlPspVQNIcce" geometry={gltf.nodes.SysBlPspVQNIcce.geometry} material={gltf.materials.ujsvqBWRMnqdwPx_0_1} />
                            <T.Mesh name="vELORlCJixqPHsZ" geometry={gltf.nodes.vELORlCJixqPHsZ.geometry} material={gltf.materials.zFdeDaGNRwzccye_0_1} />
                          </T.Group>
                          <T.Group name="tqKcchoqxZAjtuJ">
                            <T.Mesh name="IMPDFDiRXhPIUMV" geometry={gltf.nodes.IMPDFDiRXhPIUMV.geometry} material={gltf.materials.hUlRcbieVuIiOXG_0_1} />
                            <T.Mesh name="EbQGKrWAqhBHiMv" geometry={gltf.nodes.EbQGKrWAqhBHiMv.geometry} material={gltf.materials.TBLSREBUyLMVtJa_0_1} />
                            <T.Mesh name="EddVrWkqZTlvmci" geometry={gltf.nodes.EddVrWkqZTlvmci.geometry} material={gltf.materials.xNrofRCqOXXHVZt_0_1} />
                            <T.Mesh name="aGrbyjnzqoVJenz" geometry={gltf.nodes.aGrbyjnzqoVJenz.geometry} material={gltf.materials.xNrofRCqOXXHVZt_0_1} />
                            <T.Mesh name="KSWlaxBcnPDpFCs" geometry={gltf.nodes.KSWlaxBcnPDpFCs.geometry} material={gltf.materials.yQQySPTfbEJufve_0_1} />
                          </T.Group>
                          <T.Group name="jDbFLXkDWIFxkkS">
                            <T.Mesh name="AQkWXGdRSkSZMav" geometry={gltf.nodes.AQkWXGdRSkSZMav.geometry} material={gltf.materials.ujsvqBWRMnqdwPx_0_1} />
                          </T.Group>
                          <T.Mesh name="DjdhycfQYjKMDyn" geometry={gltf.nodes.DjdhycfQYjKMDyn.geometry} material={gltf.materials.ujsvqBWRMnqdwPx_0_1} />
                          <T.Mesh name="usFLmqcyrnltBUr" geometry={gltf.nodes.usFLmqcyrnltBUr.geometry} material={gltf.materials.sxNzrmuTqVeaXdg_0_1} />
                        </T.Group>
                        <T.Group name="AeiRnzwRtMFJBlp">
                          <T.Group name="lFhazxDamUcxZIL">
                            <T.Mesh name="TakBsdEjEytCAMK" geometry={gltf.nodes.TakBsdEjEytCAMK.geometry} material={gltf.materials.ZQfGMLaFcpPaLMU_0_1} />
                            <T.Mesh name="IykfmVvLplTsTEW" geometry={gltf.nodes.IykfmVvLplTsTEW.geometry} material={gltf.materials.dwrMminMXjXXeek_0_1} />
                          </T.Group>
                          <T.Group name="PzwwYtxiYzbngZl">
                            <T.Mesh name="wLfSXtbwRlBrwof" geometry={gltf.nodes.wLfSXtbwRlBrwof.geometry} material={gltf.materials.oZRkkORNzkufnGD} />
                            <T.Mesh name="WJwwVjsahIXbJpU" geometry={gltf.nodes.WJwwVjsahIXbJpU.geometry} material={gltf.materials.yhcAXNGcJWCqtIS} />
                            <T.Mesh name="cibcwsZWGgGfpme" geometry={gltf.nodes.cibcwsZWGgGfpme.geometry} material={gltf.materials.ZQfGMLaFcpPaLMU_0_1} />
                            <T.Mesh name="YfrJNXgMvGOAfzz" geometry={gltf.nodes.YfrJNXgMvGOAfzz.geometry} material={gltf.materials.bCgzXjHOanGdTFV_0_1} />
                            <T.Mesh name="DCLCbjzqejuvsqH" geometry={gltf.nodes.DCLCbjzqejuvsqH.geometry} material={gltf.materials.vhaEJjZoqGtyLdo_0_1} />
                            <T.Mesh name="dkQXkqysxzfHFiP" geometry={gltf.nodes.dkQXkqysxzfHFiP.geometry} material={gltf.materials.hUlRcbieVuIiOXG_0_1} />
                            <T.Mesh name="FscwyiLIVNWUuKe" geometry={gltf.nodes.FscwyiLIVNWUuKe.geometry} material={gltf.materials.fkUApOHLQsMUdfd_0_1} />
                          </T.Group>
                          <T.Group name="DkixFPrDptubOHd">
                            <T.Group name="UWqABIyaOofdVYc">
                              <T.Mesh name="CdalkzDVnwgdEhS" geometry={gltf.nodes.CdalkzDVnwgdEhS.geometry} material={gltf.materials.jlzuBkUzuJqgiAK_0_1} />
                              <T.Mesh name="NtjcIgolNGgYlCg" geometry={gltf.nodes.NtjcIgolNGgYlCg.geometry} material={gltf.materials.PpwUTnTFZJXxCoE} />
                              <T.Mesh name="zOPceDOPdLNSscX" geometry={gltf.nodes.zOPceDOPdLNSscX.geometry} material={gltf.materials.eShKpuMNVJTRrgg} />
                              <T.Mesh name="bxjlJpbNESedyat" geometry={gltf.nodes.bxjlJpbNESedyat.geometry} material={gltf.materials.xNrofRCqOXXHVZt_0_1} />
                              <T.Mesh name="ehFpgEdYijLjwka" geometry={gltf.nodes.ehFpgEdYijLjwka.geometry} material={gltf.materials.xNrofRCqOXXHVZt_0_1} />
                              <T.Mesh name="IXWuqsIeTqBFLIy" geometry={gltf.nodes.IXWuqsIeTqBFLIy.geometry} material={gltf.materials.EuTsEfyoAnyJIih_0_1} />
                              <T.Mesh name="qlwPlhojsxIgqwa" geometry={gltf.nodes.qlwPlhojsxIgqwa.geometry} material={gltf.materials.EszxgwYUTxbhBrC_0_1} />
                              <T.Mesh name="bpqFtgUKAOOPYpk" geometry={gltf.nodes.bpqFtgUKAOOPYpk.geometry} material={gltf.materials.yQQySPTfbEJufve_0_1} />
                              <T.Mesh name="dxVZiHfQBLkPYHO" geometry={gltf.nodes.dxVZiHfQBLkPYHO.geometry} material={gltf.materials.hUlRcbieVuIiOXG_0_1} />
                              <T.Mesh name="guvLdFXlBjMoNra" geometry={gltf.nodes.guvLdFXlBjMoNra.geometry} material={gltf.materials.fkUApOHLQsMUdfd_0_1} />
                            </T.Group>
                            <T.Group name="opnyVnejEsnQETV">
                              <T.Mesh name="PRPzbUhYhabBDYt" geometry={gltf.nodes.PRPzbUhYhabBDYt.geometry} material={gltf.materials.jlzuBkUzuJqgiAK_0_1} />
                              <T.Mesh name="oOTDgAlTGbFYzBo" geometry={gltf.nodes.oOTDgAlTGbFYzBo.geometry} material={gltf.materials.PpwUTnTFZJXxCoE} />
                              <T.Mesh name="hGKQDeRmDnGNdjb" geometry={gltf.nodes.hGKQDeRmDnGNdjb.geometry} material={gltf.materials.eShKpuMNVJTRrgg} />
                              <T.Mesh name="XRoKUoMkItkzNYL" geometry={gltf.nodes.XRoKUoMkItkzNYL.geometry} material={gltf.materials.jlzuBkUzuJqgiAK_0_1} />
                              <T.Mesh name="FjtgRCsnzEoHpCy" geometry={gltf.nodes.FjtgRCsnzEoHpCy.geometry} material={gltf.materials.xNrofRCqOXXHVZt_0_1} />
                              <T.Mesh name="gJeeYWdxrKsnsVD" geometry={gltf.nodes.gJeeYWdxrKsnsVD.geometry} material={gltf.materials.xNrofRCqOXXHVZt_0_1} />
                              <T.Mesh name="KOgQmlOdVEyKocf" geometry={gltf.nodes.KOgQmlOdVEyKocf.geometry} material={gltf.materials.jlzuBkUzuJqgiAK_0_1} />
                              <T.Mesh name="gTmqYtKthFeRVJL" geometry={gltf.nodes.gTmqYtKthFeRVJL.geometry} material={gltf.materials.xNrofRCqOXXHVZt_0_1} />
                              <T.Mesh name="obVkazjvaXyXFtA" geometry={gltf.nodes.obVkazjvaXyXFtA.geometry} material={gltf.materials.EuTsEfyoAnyJIih_0_1} />
                              <T.Mesh name="zFlMfSCaOdRDBFx" geometry={gltf.nodes.zFlMfSCaOdRDBFx.geometry} material={gltf.materials.EszxgwYUTxbhBrC_0_1} />
                              <T.Mesh name="ooeiSEXgcJckXsp" geometry={gltf.nodes.ooeiSEXgcJckXsp.geometry} material={gltf.materials.yQQySPTfbEJufve_0_1} />
                              <T.Mesh name="lfXEACUihtLFGfq" geometry={gltf.nodes.lfXEACUihtLFGfq.geometry} material={gltf.materials.hUlRcbieVuIiOXG_0_1} />
                              <T.Mesh name="eWbcqPskBBXuZDe" geometry={gltf.nodes.eWbcqPskBBXuZDe.geometry} material={gltf.materials.fkUApOHLQsMUdfd_0_1} />
                            </T.Group>
                            <T.Group name="GekGWBPcEuQbIrR">
                              <T.Mesh name="AdjkxvMXIDEHBMM" geometry={gltf.nodes.AdjkxvMXIDEHBMM.geometry} material={gltf.materials.eShKpuMNVJTRrgg} />
                              <T.Mesh name="drpRvcOgsocXGbn" geometry={gltf.nodes.drpRvcOgsocXGbn.geometry} material={gltf.materials.PpwUTnTFZJXxCoE} />
                              <T.Mesh name="KXVnYLSfTdVnSOf" geometry={gltf.nodes.KXVnYLSfTdVnSOf.geometry} material={gltf.materials.jlzuBkUzuJqgiAK_0_1} />
                              <T.Mesh name="FFAjDZTPwYrUKAV" geometry={gltf.nodes.FFAjDZTPwYrUKAV.geometry} material={gltf.materials.xNrofRCqOXXHVZt_0_1} />
                              <T.Mesh name="AwsQCWysocWlYzN" geometry={gltf.nodes.AwsQCWysocWlYzN.geometry} material={gltf.materials.xNrofRCqOXXHVZt_0_1} />
                              <T.Mesh name="wJqHahKxdxecSAC" geometry={gltf.nodes.wJqHahKxdxecSAC.geometry} material={gltf.materials.EuTsEfyoAnyJIih_0_1} />
                              <T.Mesh name="SRYqzKwamLGuEGm" geometry={gltf.nodes.SRYqzKwamLGuEGm.geometry} material={gltf.materials.EszxgwYUTxbhBrC_0_1} />
                              <T.Mesh name="yxqQUnbopbiRvZr" geometry={gltf.nodes.yxqQUnbopbiRvZr.geometry} material={gltf.materials.yQQySPTfbEJufve_0_1} />
                              <T.Mesh name="xtMgDHhPqFLAHyB" geometry={gltf.nodes.xtMgDHhPqFLAHyB.geometry} material={gltf.materials.hUlRcbieVuIiOXG_0_1} />
                              <T.Mesh name="nnqwwoLVdMJlHIF" geometry={gltf.nodes.nnqwwoLVdMJlHIF.geometry} material={gltf.materials.fkUApOHLQsMUdfd_0_1} />
                            </T.Group>
                            <T.Group name="rMbqHxTbHeRAIuc">
                              <T.Mesh name="pXBNoLiaMwsDHRF" geometry={gltf.nodes.pXBNoLiaMwsDHRF.geometry} material={gltf.materials.yiDkEwDSyEhavuP} />
                              <T.Mesh name="SCoTCDlNLPQMMyt" geometry={gltf.nodes.SCoTCDlNLPQMMyt.geometry} material={gltf.materials.yiDkEwDSyEhavuP} />
                              <T.Mesh name="fdZyCEcqJDKBWVW" geometry={gltf.nodes.fdZyCEcqJDKBWVW.geometry} material={gltf.materials.hUlRcbieVuIiOXG_0_1} />
                            </T.Group>
                            <T.Group name="iVIwUpzUeaqgBWi">
                              <T.Mesh name="IkoiNqATMVoZFKD" geometry={gltf.nodes.IkoiNqATMVoZFKD.geometry} material={gltf.materials.hiVunnLeAHkwGEo} />
                              <T.Mesh name="rqgRAGHOwnuBypi" geometry={gltf.nodes.rqgRAGHOwnuBypi.geometry} material={gltf.materials.HGhEhpqSBZRnjHC} />
                              <T.Mesh name="npMJxzurVJQlumk" geometry={gltf.nodes.npMJxzurVJQlumk.geometry} material={gltf.materials.JJvGZqtXqnnFakR_0_1} />
                            </T.Group>
                          </T.Group>
                        </T.Group>
                        <T.Mesh name="ttmRoLdJipiIOmf" geometry={gltf.nodes.ttmRoLdJipiIOmf.geometry} material={gltf.materials.hUlRcbieVuIiOXG_0_1} />
                      </T.Group>
                    </T.Group>
                  </T.Group>
                </T.Group>
              </T.Group>
            </T.Group>
          </T.Group>
        </T.Group>
      {/if}
      {#if settings?.devices?.macbookEnabled !== false}
        <T.Group name="macbook" position={[3, -0.16, 0]} rotation={[-Math.PI + macbookRotation[0], macbookRotation[1], -Math.PI + macbookRotation[2]]} scale={26.97}>
          <T.Group name="Sketchfab_model_1" rotation={[-Math.PI / 2, 0, 0]}>
            <T.Group name="root">
              <T.Group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                <!-- Needs to be -0.11 -->
                <T.Group name="Bevels_2" position={[0, 0.01, -0.1]} scale={0.27}>
                  <T.Group name="Empty_1" rotation={[-Math.PI, 0, 0]} scale={[-0.04, 0.04, 0.04]}>
                    <T.Group name="Camera_Light_0" position={[0, 0.08, -0.04]} rotation={[-1.19, 0, 0]} scale={[-25.38, 25.38, 25.38]}>
                      <T.Mesh name="Object_12" geometry={gltf.nodes.Object_12.geometry} material={gltf.materials.Camera_Light_0_1} />
                    </T.Group>
                  </T.Group>
                  <T.Mesh name="Object_4" geometry={gltf.nodes.Object_4.geometry} material={gltf.materials.Black_Glass_0_1} />
                  <T.Mesh name="Object_5" geometry={gltf.nodes.Object_5.geometry} material={gltf.materials.Black_Plastic_0_1} />
                  <T.Mesh name="Object_6" geometry={gltf.nodes.Object_6.geometry} material={gltf.materials.Glass_0_1} />
                  <T.Mesh name="Object_7" geometry={gltf.nodes.Object_7.geometry} material={gltf.materials["Material.002_0_1"]} />
                  <T.Mesh name="Object_8" geometry={gltf.nodes.Object_8.geometry} material={gltf.materials.Space_Grey_0_1} />
                  <T.Mesh name="Object_9" geometry={gltf.nodes.Object_9.geometry} material={gltf.materials["Space_Grey.001_0_1"]} />
                </T.Group>
                <T.Group name="Circle001_12" position={[0.2, 0.01, -0.1]} rotation={[0.01, -0.75, 1.27]} />
                <T.Group name="Caps_Lock_Light_3" position={[0, -0.01, 0]} scale={0.27}>
                  <T.Mesh name="Object_14" geometry={gltf.nodes.Object_14.geometry} material={gltf.materials.Caps_Lock_Light_0_1} />
                </T.Group>
                <T.Group name="Macbook_Pro_4" position={[0, 0.01, -0.1]} rotation={[1.95, 0, 0]} scale={0.27}>
                  <T.Mesh name="Object_16" geometry={gltf.nodes.Object_16.geometry} material={gltf.materials["Material.001_0_1"]} />
                </T.Group>
                <T.Group name="Main_Body_5" position={[0, -0.01, 0]} scale={0.27}>
                  <T.Mesh name="Object_18" geometry={gltf.nodes.Object_18.geometry} material={gltf.materials.Space_Grey_0_1} />
                  <T.Mesh name="Object_19" geometry={gltf.nodes.Object_19.geometry} material={gltf.materials.Black_Plastic_0_1} />
                  <T.Mesh name="Object_20" geometry={gltf.nodes.Object_20.geometry} material={gltf.materials.Black_Plastic_0_1} />
                  <T.Mesh name="Object_21" geometry={gltf.nodes.Object_21.geometry} material={gltf.materials["Keys.001_0_1"]} />
                </T.Group>
                <T.Group name="Touch_Bar_6" position={[0, -0.01, 0]} scale={0.27}>
                  <T.Mesh name="Object_23" geometry={gltf.nodes.Object_23.geometry} material={gltf.materials.Black_Plastic_0_1} />
                  <T.Mesh name="Object_24" geometry={gltf.nodes.Object_24.geometry} material={gltf.materials.Black_Glass_0_1} />
                  <T.Mesh name="Object_25" geometry={gltf.nodes.Object_25.geometry} material={gltf.materials.Keys_0_1} />
                </T.Group>
                <T.Group name="Touch_Bar_Shot_7" position={[0, -0.01, 0]} scale={0.27}>
                  <T.Mesh name="Object_27" geometry={gltf.nodes.Object_27.geometry} material={gltf.materials["Touch_Bar_Shot_2021-04-02_at_18.13.28_0_1"]} />
                </T.Group>
                <T.Group name="Keyboard_8" position={[0, -0.01, 0]} scale={0.27}>
                  <T.Mesh name="Object_29" geometry={gltf.nodes.Object_29.geometry} material={gltf.materials.Black_Plastic_0_1} />
                  <T.Mesh name="Object_30" geometry={gltf.nodes.Object_30.geometry} material={gltf.materials.Keys_0_1} />
                </T.Group>
                <T.Group name="Cube_9" position={[0, -0.01, 0]}>
                  <T.Mesh name="Object_32" geometry={gltf.nodes.Object_32.geometry} material={gltf.materials.Black_Plastic_0_1} />
                </T.Group>
              </T.Group>
            </T.Group>
          </T.Group>
        </T.Group>
      {/if}
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
